name: snapgram
description: Offline-first Flutter Instagram clone with Supabase and PowerSync.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.3.1 <4.0.0"

dependencies:
  animations:
  app_ui:
    path: packages/app_ui
  async:
  bloc:
  cached_memory_image:
  cached_network_image: 3.4.1
  carousel_slider_plus: ^6.0.0
  chats_repository:
    path: packages/chats_repository
  collection:
  database_client:
    path: packages/database_client
  env:
    path: packages/env
  equatable: ^2.0.5
  fast_immutable_collections:
  firebase_core: ^2.31.1
  firebase_messaging:
  firebase_notifications_client:
    path: packages/notifications_client/firebase_notifications_client
  firebase_remote_config_repository:
    path: packages/firebase_remote_config_repository
  flex_color_scheme:
  flutter:
    sdk: flutter
  flutter_animate:
  flutter_bloc:
  flutter_localizations:
    sdk: flutter
  flutter_markdown:
  flutter_portal:
  flutter_staggered_grid_view:
  form_fields:
    path: packages/form_fields
  get_it:
  go_router:
  google_sign_in: ^6.2.1
  gotrue: ^2.8.3
  hydrated_bloc:
  intl:
  insta_blocks:
    path: packages/insta_blocks
  instagram_blocks_ui:
    path: packages/instagram_blocks_ui
  inview_notifier_list:
    git: https://github.com/Gambley1/inview_notifier_list
  json_annotation:
  lottie:
  notifications_repository:
    path: packages/notifications_repository
  ogp_data_extract:
  palette_generator:
  path_provider:
  persistent_storage:
    path: packages/storage/persistent_storage
  posts_repository:
    path: packages/posts_repository
  powersync_repository:
    path: packages/powersync_repository
  scrollable_positioned_list:
  search_repository:
    path: packages/search_repository
  shared:
    path: packages/shared
  shimmer:
  slang:
  slang_flutter:
  sliver_tools:
  sprung:
  stories_editor:
    path: packages/stories_editor
  stories_repository:
    path: packages/stories_repository
  story_view:
  supabase_authentication_client:
    path: packages/authentication_client/supabase_authentication_client
  timeago:
  token_storage:
    path: packages/authentication_client/token_storage
  url_launcher:
  user_repository:
    path: packages/user_repository
  vector_math:
  visibility_detector:

dev_dependencies:
  bloc_test: ^9.1.7
  build_runner:
  build_verify:
  flutter_test:
    sdk: flutter
  json_serializable:
  mocktail:
  slang_build_runner:
  very_good_analysis:
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.1

flutter:
  uses-material-design: true
  generate: true
dependency_overrides:
  fading_edge_scrollview: ^4.1.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "packages/app_ui/assets/images/snapgram_icon.png"
  min_sdk_android: 21

flutter_native_splash:
  color: "#201e1e"
  #background_image: "assets/background.png"

  image: packages/app_ui/assets/images/snapgram_splash_icon.png

  #branding: assets/dart.png

  #branding_mode: bottom

  #color_dark: "#201e1e"
  #background_image_dark: "assets/dark-background.png"
  #image_dark: assets/splash-invert.png
  #branding_dark: assets/dart_dark.png

  android_12:
    image: packages/app_ui/assets/images/snapgram_splash_icon.png

    color: "#201e1e"

    #icon_background_color: "#111111"

    #branding: assets/dart.png

    #image_dark: assets/android12splash-invert.png
    #color_dark: "#042a49"
    #icon_background_color_dark: "#eeeeee"

  #android: false
  #ios: false
  #web: false

  #color_android: "#42a5f5"
  #color_dark_android: "#042a49"
  #color_ios: "#42a5f5"
  #color_dark_ios: "#042a49"
  #color_web: "#42a5f5"
  #color_dark_web: "#042a49"
  #image_android: assets/splash-android.png
  #image_dark_android: assets/splash-invert-android.png
  #image_ios: assets/splash-ios.png
  #image_dark_ios: assets/splash-invert-ios.png
  #image_web: assets/splash-web.gif
  #image_dark_web: assets/splash-invert-web.gif
  #background_image_android: "assets/background-android.png"
  #background_image_dark_android: "assets/dark-background-android.png"
  #background_image_ios: "assets/background-ios.png"
  #background_image_dark_ios: "assets/dark-background-ios.png"
  #background_image_web: "assets/background-web.png"
  #background_image_dark_web: "assets/dark-background-web.png"
  #branding_android: assets/brand-android.png
  #branding_bottom_padding_android: 24
  #branding_dark_android: assets/dart_dark-android.png
  #branding_ios: assets/brand-ios.png
  #branding_bottom_padding_ios: 24
  #branding_dark_ios: assets/dart_dark-ios.png
  #branding_web: assets/brand-web.gif
  #branding_dark_web: assets/dart_dark-web.gif

  #
  #android_gravity: center
  #
  #ios_content_mode: center
  #
  #web_image_mode: center

  #android_screen_orientation: sensorLandscape

  #fullscreen: true

  #info_plist_files:
