// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_prod.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTrub8ilq3rvxVfWurqE5Q3KfnXSYbk8I',
    appId: '1:67737138623:web:3caf9caad52e4075f01d0a',
    messagingSenderId: '67737138623',
    projectId: 'snapgram-prod',
    authDomain: 'snapgram-prod.firebaseapp.com',
    storageBucket: 'snapgram-prod.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArcEMVIZjInUljwDVEt3RI_3PZLWjBp9o',
    appId: '1:67737138623:android:5a46dc8f678b8276f01d0a',
    messagingSenderId: '67737138623',
    projectId: 'snapgram-prod',
    storageBucket: 'snapgram-prod.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0kRa_zpYrGhdXYBtZlj_tshN-aHKX43g',
    appId: '1:67737138623:ios:fb738e38a957ec4bf01d0a',
    messagingSenderId: '67737138623',
    projectId: 'snapgram-prod',
    storageBucket: 'snapgram-prod.appspot.com',
    iosClientId: '67737138623-bvvhjlt3cmlm4cjem8ul90h2bvk46m6p.apps.googleusercontent.com',
    iosBundleId: 'com.devshubh69.snapgram',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0kRa_zpYrGhdXYBtZlj_tshN-aHKX43g',
    appId: '1:67737138623:ios:8c2d70c12ce06ce6f01d0a',
    messagingSenderId: '67737138623',
    projectId: 'snapgram-prod',
    storageBucket: 'snapgram-prod.appspot.com',
    iosClientId: '67737138623-fqjh3ffscnn19fpb4a3pohf5ja1vffsm.apps.googleusercontent.com',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBTrub8ilq3rvxVfWurqE5Q3KfnXSYbk8I',
    appId: '1:67737138623:web:437e32f16b50b4c5f01d0a',
    messagingSenderId: '67737138623',
    projectId: 'snapgram-prod',
    authDomain: 'snapgram-prod.firebaseapp.com',
    storageBucket: 'snapgram-prod.appspot.com',
  );
}
