name: env
description: Repository to manage environment variables.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.4.0
  flutter: ^3.22.0

dependencies:
  envied:
  flutter:
    sdk: flutter

dev_dependencies:
  build_runner:
  envied_generator: 
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0
